// Governance Oracle Types

export type MetricCategory = 
  | 'onchain' 
  | 'social' 
  | 'github' 
  | 'game' 
  | 'custom'

export type MetricType = 
  | 'tvl'
  | 'unique_users'
  | 'transaction_count'
  | 'token_holders'
  | 'daily_active_users'
  | 'revenue'
  | 'twitter_followers'
  | 'twitter_engagement'
  | 'discord_members'
  | 'discord_activity'
  | 'telegram_members'
  | 'sentiment_score'
  | 'github_commits'
  | 'github_contributors'
  | 'github_stars'
  | 'github_releases'
  | 'custom_metric'

export type ConditionOperator = 
  | 'greater_than'
  | 'less_than'
  | 'equals'
  | 'greater_or_equal'
  | 'less_or_equal'
  | 'not_equals'
  | 'increased_by_percent'
  | 'decreased_by_percent'
  | 'sustained_above'
  | 'sustained_below'

export type LogicalOperator = 'AND' | 'OR'

export type OutputType = 'boolean' | 'score' | 'raw_value'

// Icon names from Lucide - rendered as components in UI
// Note: 'XLogo' is a custom component for X (formerly Twitter)
export type MetricIconName = 
  | 'Wallet'
  | 'Users'
  | 'BarChart3'
  | 'Coins'
  | 'TrendingUp'
  | 'DollarSign'
  | 'XLogo'
  | 'MessageCircle'
  | 'Gamepad2'
  | 'MessagesSquare'
  | 'Send'
  | 'Smile'
  | 'GitCommit'
  | 'UserCheck'
  | 'Star'
  | 'Rocket'
  | 'Settings'

export interface MetricSource {
  id: string
  name: string
  category: MetricCategory
  type: MetricType
  description: string
  unit?: string
  apiEndpoint?: string
  iconName: MetricIconName
  currentValue?: number
  sampleValue: number
}

export interface Condition {
  id: string
  metricId: string
  operator: ConditionOperator
  value: number
  duration?: number // For sustained conditions (in days)
  durationUnit?: 'hours' | 'days' | 'weeks'
}

export interface ConditionGroup {
  id: string
  conditions: Condition[]
  logicalOperator: LogicalOperator
}

export interface GovernanceOutput {
  type: OutputType
  // For boolean
  trueLabel?: string
  falseLabel?: string
  // For score
  minScore?: number
  maxScore?: number
  // For raw value
  decimals?: number
  unit?: string
}

export interface GovernanceTemplate {
  id: string
  name: string
  description: string
  iconName: MetricIconName
  category: string
  metrics: MetricSource[]
  conditions: ConditionGroup[]
  output: GovernanceOutput
  useCases: string[]
}

export interface GovernanceOracleConfig {
  id: string
  name: string
  description: string
  templateId?: string
  
  // Data sources
  metrics: MetricSource[]
  customInputs: {
    protocolAddress?: string
    twitterHandle?: string
    discordServerId?: string
    githubRepo?: string
    customApiEndpoint?: string
  }
  
  // Conditions
  conditionGroups: ConditionGroup[]
  rootLogicalOperator: LogicalOperator
  
  // Output configuration
  output: GovernanceOutput
  
  // Deployment
  network: string
  updateInterval: number
  
  // DAO Integration
  daoIntegration?: {
    type: 'realms' | 'metadao' | 'squads' | 'spl_governance' | 'custom'
    proposalId?: string
    treasuryAddress?: string
  }
}

// Predefined metric sources
export const METRIC_SOURCES: MetricSource[] = [
  // On-chain metrics
  {
    id: 'tvl',
    name: 'Total Value Locked',
    category: 'onchain',
    type: 'tvl',
    description: 'Total value locked in the protocol',
    unit: 'USD',
    iconName: 'Wallet',
    sampleValue: 1500000,
  },
  {
    id: 'unique_users',
    name: 'Unique Users',
    category: 'onchain',
    type: 'unique_users',
    description: 'Number of unique wallet addresses',
    iconName: 'Users',
    sampleValue: 5420,
  },
  {
    id: 'transaction_count',
    name: 'Transaction Count',
    category: 'onchain',
    type: 'transaction_count',
    description: 'Total number of transactions',
    iconName: 'BarChart3',
    sampleValue: 125000,
  },
  {
    id: 'token_holders',
    name: 'Token Holders',
    category: 'onchain',
    type: 'token_holders',
    description: 'Number of addresses holding the token',
    iconName: 'Coins',
    sampleValue: 8900,
  },
  {
    id: 'daily_active_users',
    name: 'Daily Active Users',
    category: 'onchain',
    type: 'daily_active_users',
    description: 'Unique users in the last 24 hours',
    iconName: 'TrendingUp',
    sampleValue: 342,
  },
  {
    id: 'revenue',
    name: 'Protocol Revenue',
    category: 'onchain',
    type: 'revenue',
    description: 'Revenue generated by the protocol',
    unit: 'USD',
    iconName: 'DollarSign',
    sampleValue: 45000,
  },
  
  // Social metrics
  {
    id: 'twitter_followers',
    name: 'X Verified Followers',
    category: 'social',
    type: 'twitter_followers',
    description: 'Number of verified (blue check) X followers',
    iconName: 'UserCheck',
    sampleValue: 1250,
  },
  {
    id: 'twitter_engagement',
    name: 'X Engagement',
    category: 'social',
    type: 'twitter_engagement',
    description: 'Average engagement rate on posts',
    unit: '%',
    iconName: 'MessageCircle',
    sampleValue: 4.5,
  },
  {
    id: 'discord_members',
    name: 'Discord Members',
    category: 'social',
    type: 'discord_members',
    description: 'Total Discord server members',
    iconName: 'Gamepad2',
    sampleValue: 12500,
  },
  {
    id: 'discord_activity',
    name: 'Discord Activity',
    category: 'social',
    type: 'discord_activity',
    description: 'Messages per day in Discord',
    iconName: 'MessagesSquare',
    sampleValue: 850,
  },
  {
    id: 'telegram_members',
    name: 'Telegram Members',
    category: 'social',
    type: 'telegram_members',
    description: 'Total Telegram group members',
    iconName: 'Send',
    sampleValue: 8500,
  },
  {
    id: 'sentiment_score',
    name: 'Sentiment Score',
    category: 'social',
    type: 'sentiment_score',
    description: 'AI-analyzed community sentiment',
    unit: 'score',
    iconName: 'Smile',
    sampleValue: 72,
  },
  
  // GitHub metrics
  {
    id: 'github_commits',
    name: 'GitHub Commits',
    category: 'github',
    type: 'github_commits',
    description: 'Total commits in repository',
    iconName: 'GitCommit',
    sampleValue: 1250,
  },
  {
    id: 'github_contributors',
    name: 'Contributors',
    category: 'github',
    type: 'github_contributors',
    description: 'Number of repository contributors',
    iconName: 'UserCheck',
    sampleValue: 45,
  },
  {
    id: 'github_stars',
    name: 'GitHub Stars',
    category: 'github',
    type: 'github_stars',
    description: 'Repository star count',
    iconName: 'Star',
    sampleValue: 890,
  },
  {
    id: 'github_releases',
    name: 'Releases',
    category: 'github',
    type: 'github_releases',
    description: 'Number of releases published',
    iconName: 'Rocket',
    sampleValue: 24,
  },
  
  // Custom
  {
    id: 'custom_metric',
    name: 'Custom Metric',
    category: 'custom',
    type: 'custom_metric',
    description: 'Custom metric from your API',
    iconName: 'Settings',
    sampleValue: 0,
  },
]

// Predefined templates
export const GOVERNANCE_TEMPLATES: GovernanceTemplate[] = [
  {
    id: 'grant_milestone_tracker',
    name: 'Grant Milestone Tracker',
    description: 'Track project milestones for automatic grant disbursement',
    iconName: 'Star',
    category: 'Grants',
    metrics: METRIC_SOURCES.filter(m => ['tvl', 'unique_users', 'transaction_count'].includes(m.id)),
    conditions: [
      {
        id: 'cg1',
        conditions: [
          { id: 'c1', metricId: 'tvl', operator: 'greater_than', value: 1000000 },
          { id: 'c2', metricId: 'unique_users', operator: 'greater_than', value: 500 },
        ],
        logicalOperator: 'AND',
      },
    ],
    output: {
      type: 'boolean',
      trueLabel: 'Milestone Reached',
      falseLabel: 'In Progress',
    },
    useCases: [
      'Automatic grant release when TVL milestone hit',
      'Track builder progress on funded projects',
      'Performance-based funding unlocks',
    ],
  },
  {
    id: 'community_manager_performance',
    name: 'Community Manager Performance',
    description: 'Calculate performance scores for community managers',
    iconName: 'Users',
    category: 'Performance',
    metrics: METRIC_SOURCES.filter(m => ['discord_members', 'discord_activity', 'twitter_followers', 'twitter_engagement', 'sentiment_score'].includes(m.id)),
    conditions: [
      {
        id: 'cg1',
        conditions: [
          { id: 'c1', metricId: 'discord_members', operator: 'increased_by_percent', value: 10 },
          { id: 'c2', metricId: 'twitter_engagement', operator: 'greater_than', value: 3 },
        ],
        logicalOperator: 'AND',
      },
    ],
    output: {
      type: 'score',
      minScore: 0,
      maxScore: 100,
    },
    useCases: [
      'Performance-based salary bonuses',
      'Community manager competition rankings',
      'Automated contributor rewards',
    ],
  },
  {
    id: 'protocol_health_monitor',
    name: 'Protocol Health Monitor',
    description: 'Monitor overall protocol health and activity',
    iconName: 'TrendingUp',
    category: 'Monitoring',
    metrics: METRIC_SOURCES.filter(m => ['tvl', 'daily_active_users', 'revenue', 'transaction_count'].includes(m.id)),
    conditions: [
      {
        id: 'cg1',
        conditions: [
          { id: 'c1', metricId: 'tvl', operator: 'greater_than', value: 500000 },
          { id: 'c2', metricId: 'daily_active_users', operator: 'greater_than', value: 100 },
          { id: 'c3', metricId: 'revenue', operator: 'greater_than', value: 1000 },
        ],
        logicalOperator: 'AND',
      },
    ],
    output: {
      type: 'score',
      minScore: 0,
      maxScore: 100,
    },
    useCases: [
      'Automatic treasury management based on health',
      'Emergency pause triggers',
      'Investor reporting dashboards',
    ],
  },
  {
    id: 'social_growth_tracker',
    name: 'Social Growth Tracker',
    description: 'Track and verify social media growth metrics',
    iconName: 'XLogo',
    category: 'Social',
    metrics: METRIC_SOURCES.filter(m => ['twitter_followers', 'discord_members', 'telegram_members', 'sentiment_score'].includes(m.id)),
    conditions: [
      {
        id: 'cg1',
        conditions: [
          { id: 'c1', metricId: 'twitter_followers', operator: 'increased_by_percent', value: 10 },
        ],
        logicalOperator: 'AND',
      },
    ],
    output: {
      type: 'raw_value',
      decimals: 0,
    },
    useCases: [
      'Marketing campaign effectiveness',
      'Influencer partnership verification',
      'Growth-based token unlocks',
      'Verified follower milestone rewards',
    ],
  },
  {
    id: 'game_state_oracle',
    name: 'Game State Oracle',
    description: 'Create oracles for game achievements and states',
    iconName: 'Gamepad2',
    category: 'Gaming',
    metrics: [METRIC_SOURCES.find(m => m.id === 'custom_metric')!],
    conditions: [
      {
        id: 'cg1',
        conditions: [
          { id: 'c1', metricId: 'custom_metric', operator: 'greater_than', value: 0 },
        ],
        logicalOperator: 'AND',
      },
    ],
    output: {
      type: 'boolean',
      trueLabel: 'Achievement Unlocked',
      falseLabel: 'Not Yet',
    },
    useCases: [
      'NFT minting based on game progress',
      'Tournament winner verification',
      'Play-to-earn reward triggers',
    ],
  },
]

// Helper functions
export function getOperatorLabel(operator: ConditionOperator): string {
  const labels: Record<ConditionOperator, string> = {
    greater_than: '>',
    less_than: '<',
    equals: '=',
    greater_or_equal: '≥',
    less_or_equal: '≤',
    not_equals: '≠',
    increased_by_percent: '↑ %',
    decreased_by_percent: '↓ %',
    sustained_above: 'stays above',
    sustained_below: 'stays below',
  }
  return labels[operator]
}

export function getOperatorDescription(operator: ConditionOperator): string {
  const descriptions: Record<ConditionOperator, string> = {
    greater_than: 'is greater than',
    less_than: 'is less than',
    equals: 'equals',
    greater_or_equal: 'is greater than or equal to',
    less_or_equal: 'is less than or equal to',
    not_equals: 'does not equal',
    increased_by_percent: 'has increased by',
    decreased_by_percent: 'has decreased by',
    sustained_above: 'stays above for',
    sustained_below: 'stays below for',
  }
  return descriptions[operator]
}

export function evaluateCondition(
  condition: Condition, 
  currentValue: number, 
  previousValue?: number
): boolean {
  switch (condition.operator) {
    case 'greater_than':
      return currentValue > condition.value
    case 'less_than':
      return currentValue < condition.value
    case 'equals':
      return currentValue === condition.value
    case 'greater_or_equal':
      return currentValue >= condition.value
    case 'less_or_equal':
      return currentValue <= condition.value
    case 'not_equals':
      return currentValue !== condition.value
    case 'increased_by_percent':
      if (!previousValue) return false
      return ((currentValue - previousValue) / previousValue) * 100 >= condition.value
    case 'decreased_by_percent':
      if (!previousValue) return false
      return ((previousValue - currentValue) / previousValue) * 100 >= condition.value
    case 'sustained_above':
      return currentValue > condition.value // Simplified - would need historical data
    case 'sustained_below':
      return currentValue < condition.value // Simplified - would need historical data
    default:
      return false
  }
}

export function evaluateConditionGroup(
  group: ConditionGroup,
  metricValues: Record<string, number>
): boolean {
  const results = group.conditions.map(condition => {
    const value = metricValues[condition.metricId] || 0
    return evaluateCondition(condition, value)
  })
  
  if (group.logicalOperator === 'AND') {
    return results.every(r => r)
  } else {
    return results.some(r => r)
  }
}

export function formatMetricValue(value: number, metric: MetricSource): string {
  if (metric.unit === 'USD') {
    return `$${value.toLocaleString()}`
  }
  if (metric.unit === '%') {
    return `${value.toFixed(1)}%`
  }
  if (value >= 1000000) {
    return `${(value / 1000000).toFixed(2)}M`
  }
  if (value >= 1000) {
    return `${(value / 1000).toFixed(1)}K`
  }
  return value.toLocaleString()
}
